#include "KeyLookup.h"

#include <raylib.h>

const char *g_key_lookup[] {
        [KEY_NULL] = "NULL",
        [KEY_SPACE] = "SPACE",
        [KEY_APOSTROPHE] = "'",
        [KEY_COMMA] = ",",
        [KEY_MINUS] = "-",
        [KEY_PERIOD] = ".",
        [KEY_SLASH] = "/",
        [KEY_ONE] = "1",
        [KEY_TWO] = "2",
        [KEY_THREE] = "3",
        [KEY_FOUR] = "4",
        [KEY_FIVE] = "5",
        [KEY_SIX] = "6",
        [KEY_SEVEN] = "7",
        [KEY_EIGHT] = "8",
        [KEY_NINE] = "9",
        [KEY_SEMICOLON] = ";",
        [KEY_EQUAL] = "=",
        [KEY_A] = "A",
        [KEY_B] = "B",
        [KEY_C] = "C",
        [KEY_D] = "D",
        [KEY_E] = "E",
        [KEY_F] = "F",
        [KEY_G] = "G",
        [KEY_H] = "H",
        [KEY_I] = "I",
        [KEY_J] = "J",
        [KEY_K] = "K",
        [KEY_L] = "L",
        [KEY_M] = "M",
        [KEY_N] = "N",
        [KEY_O] = "O",
        [KEY_P] = "P",
        [KEY_Q] = "Q",
        [KEY_R] = "R",
        [KEY_S] = "S",
        [KEY_T] = "T",
        [KEY_U] = "U",
        [KEY_V] = "V",
        [KEY_W] = "W",
        [KEY_X] = "X",
        [KEY_Y] = "Y",
        [KEY_Z] = "Z",
        [KEY_LEFT_BRACKET] = "[",
        [KEY_BACKSLASH] = "\\",
        [KEY_RIGHT_BRACKET] = "]",
        [KEY_GRAVE] = "`",
        [KEY_ESCAPE] = "Esc",
        [KEY_ENTER] = "Enter",
        [KEY_TAB] = "Tab",
        [KEY_BACKSPACE] = "Backspace",
        [KEY_INSERT] = "Ins",
        [KEY_DELETE] = "Del",
        [KEY_RIGHT] = "Right",
        [KEY_LEFT] = "Left",
        [KEY_DOWN] = "Down",
        [KEY_UP] = "Up",
        [KEY_PAGE_UP] = "Page up",
        [KEY_PAGE_DOWN] = "Page down",
        [KEY_HOME] = "Home",
        [KEY_END] = "End",
        [KEY_CAPS_LOCK] = "Caps lock",
        [KEY_SCROLL_LOCK] = "Scroll down",
        [KEY_NUM_LOCK] = "Num lock",
        [KEY_PRINT_SCREEN] = "Print screen",
        [KEY_PAUSE] = "Pause",
};
